# parser to find the lowest energy in an energy.txt file as generated by my geometry_optimisation_cubic file
# written by Pascal Salzbrenner - pts28@cam.ac.uk

energyfile = open("energy.txt", "r")

first_line = energyfile.readline()
lowest_energy_lattice_parameter = float(first_line.split()[0])
lowest_energy = float(first_line.split()[1])

for line in energyfile:

    energy = float(line.split()[1])
    if energy < lowest_energy:
        lowest_energy = energy
        lowest_energy_lattice_parameter = float(line.split()[0])

energyfile.close()

with open("lowest_energy.txt", "w") as outfile:
    outfile.write("The lowest energy is {}. It occurs at a lattice parameter of {} Angstrom.".format(
    lowest_energy, lowest_energy_lattice_parameter))
